# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Dev Notes
# email: your-email@domain.com
description: My Dev notes that might be useful for you too!
baseurl: ""
url: "http://mydevnotes.com"
github_username:  yorkshireman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
